#!/bin/bash

#Copyright (C) 2012 Vipin Nair <swvist@gmail.com>

#Permission is hereby granted, free of charge, to any person obtaining a copy of
#this software and associated documentation files (the "Software"), to deal in
#the Software without restriction, including without limitation the rights to
#use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
#of the Software, and to permit persons to whom the Software is furnished to do
#so, subject to the following conditions:

#The above copyright notice and this permission notice shall be included in all
#copies or substantial portions of the Software.

#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
#SOFTWARE.


if		[ ! -n $1 ]
then	echo "File Name Required. Aborting."
		exit 1
else	if 	[ ! -f $1.l ]
			then	echo "$1.l not found. Aborting."
					exit 1
			else 	echo "Checking for previous flex build."
					if	[ -f lex.yy.c ]
						then	echo "Previous flex build found."
								rm lex.yy.c
								echo "Deleted."
						else	echo "No previous build found."
					fi
					echo "Processing $1.l using Flex."
					flex $1.l
					if	[ -f lex.yy.c ]
						then	echo "Success."
						else 	echo "Error. Process Failed. Aborting."
						exit 1
					fi
		fi


		if 	[ ! -f $1.y ]
			then	echo "$1.y not found. Aborting."
					exit 1
			else 	echo "Checking for previous Yacc build."
					if	[ -f $1.tab.c ]
						then	echo "Previous Yacc build found."
								rm $1.tab.c
								echo "Deleted."
					fi
					if	[ -f y.tab.h ]
						then	echo "Previous Yacc build found."
								rm y.tab.h
								echo "Deleted."
					fi
					echo "Processing $1.y using Bison."
					bison --defines=y.tab.h $1.y
					if	[ -f $1.tab.c ] && [ -f y.tab.h ]
						then	echo "Success."
						else 	echo "Error. Process Failed. Aborting."
								exit 1
					fi
		fi

		echo "Checking for previous Executable."
		if	[ -f a.out ]
			then	echo "Previous executable found, Deleting."
					rm a.out
					if	[ ! -f a.out ]
						then	echo "Deleted."
						else	echo "Unable to Delete. Check file permissions."
					fi
		fi
		echo "Compiling source code."
		gcc lex.yy.c $1.tab.c
		if	[ -f a.out ]
			then	echo "Success."
					echo  "Running the executable."
					./a.out
			else	echo "Error. Process Failed. Aborting."
					exit 1
		fi
fi
